In [21]:
import csv
import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim

In [8]:
df = pd.read_csv('massshootings.csv', encoding = 'ISO-8859-1', parse_dates = ['Date'])

In [9]:
df.head()

,S#,Title,Location,Date,Incident Area,Open/Close Location,Target,Cause,Summary,Fatalities,...,Total victims,Policeman Killed,Age,Employeed (Y/N),Employed at,Mental Health Issues,Race,Gender,Latitude,Longitude
0,1,Texas church mass shooting,"Sutherland Springs, TX",2017-11-05,Church,Close,random,unknown,"Devin Patrick Kelley, 26, an ex-air force offi...",26,...,46,0.0,26,NaN,NaN,No,White,M,NaN,NaN
1,2,Walmart shooting in suburban Denver,"Thornton, CO",2017-11-01,Wal-Mart,Open,random,unknown,"Scott Allen Ostrem, 47, walked into a Walmart ...",3,...,3,0.0,47,NaN,NaN,No,White,M,NaN,NaN
2,3,Edgewood businees park shooting,"Edgewood, MD",2017-10-18,Remodeling Store,Close,coworkers,unknown,"Radee Labeeb Prince, 37, fatally shot three pe...",3,...,6,0.0,37,NaN,Advance Granite Store,No,Black,M,NaN,NaN
3,4,Las Vegas Strip mass shooting,"Las Vegas, NV",2017-10-01,Las Vegas Strip Concert outside Mandala Bay,Open,random,unknown,"Stephen Craig Paddock, opened fire from the 32...",59,...,585,1.0,64,NaN,NaN,Unclear,White,M,36.181271,-115.134132
4,5,San Francisco UPS shooting,"San Francisco, CA",2017-06-14,UPS facility,Close,coworkers,NaN,"Jimmy Lam, 38, fatally shot three coworkers an...",3,...,5,0.0,38,1.0,NaN,Yes,Asian,M,NaN,NaN

In [10]:
df.columns

Index(['S#', 'Title', 'Location', 'Date', 'Incident Area',
       'Open/Close Location', 'Target', 'Cause', 'Summary', 'Fatalities',
       'Injured', 'Total victims', 'Policeman Killed', 'Age',
       'Employeed (Y/N)', 'Employed at', 'Mental Health Issues', 'Race',
       'Gender', 'Latitude', 'Longitude'],
      dtype='object')

In [11]:
geolocator = Nominatim()

In [12]:
location = geolocator.geocode("175 5th Avenue NYC")
print(location.address)
print((location.latitude, location.longitude))

Flatiron Building, 175, 5th Avenue, Flatiron Building, Manhattan Community Board 5, New York County, NYC, New York, 10010, United States of America
(40.7410861, -73.9896298241625)

In [17]:
df.isnull().sum()

S#                        0
Title                     0
Location                 45
Date                      0
Incident Area            62
Open/Close Location      28
Target                    5
Cause                    77
Summary                   0
Fatalities                0
Injured                   0
Total victims             0
Policeman Killed          6
Age                     144
Employeed (Y/N)         256
Employed at             282
Mental Health Issues      0
Race                      2
Gender                    0
Latitude                 20
Longitude                20
dtype: int64

In [18]:
df.loc[96]

S#                                                                     97
Title                                   Clearbrook (Greenwood), Minnesota
Location                                Clearbrook (Greenwood), Minnesota
Date                                                  2015-09-10 00:00:00
Incident Area                                                        Home
Open/Close Location                                                 Close
Target                                                             random
Cause                                                                 NaN
Summary                 Five family members - two adults and three chi...
Fatalities                                                              5
Injured                                                                 0
Total victims                                                           4
Policeman Killed                                                        0
Age                                                                   NaN
Employeed (Y/N)                                                         1
Employed at                                                           NaN
Mental Health Issues                                                  Yes
Race                                  White American or European American
Gender                                                               Male
Latitude                                                          47.6962
Longitude                                                        -95.4284
Name: 96, dtype: object

In [46]:
def fill_LatLong(row):
    if (row['Latitude'] != row['Latitude'] or row['Longitude'] != row['Longitude']):
        location = geolocator.geocode(row['Location'])
        row['Latitude'] = location.latitude
        row['Longitude'] = location.longitude
    return row

In [47]:
df.apply(lambda row: fill_LatLong(row), axis = 1)

,S#,Title,Location,Date,Incident Area,Open/Close Location,Target,Cause,Summary,Fatalities,...,Total victims,Policeman Killed,Age,Employeed (Y/N),Employed at,Mental Health Issues,Race,Gender,Latitude,Longitude
0,1,Texas church mass shooting,"Sutherland Springs, TX",2017-11-05,Church,Close,random,unknown,"Devin Patrick Kelley, 26, an ex-air force offi...",26,...,46,0.0,26,NaN,NaN,No,White,M,29.274044,-98.055906
1,2,Walmart shooting in suburban Denver,"Thornton, CO",2017-11-01,Wal-Mart,Open,random,unknown,"Scott Allen Ostrem, 47, walked into a Walmart ...",3,...,3,0.0,47,NaN,NaN,No,White,M,39.957821,-104.966989
2,3,Edgewood businees park shooting,"Edgewood, MD",2017-10-18,Remodeling Store,Close,coworkers,unknown,"Radee Labeeb Prince, 37, fatally shot three pe...",3,...,6,0.0,37,NaN,Advance Granite Store,No,Black,M,39.418719,-76.294402
3,4,Las Vegas Strip mass shooting,"Las Vegas, NV",2017-10-01,Las Vegas Strip Concert outside Mandala Bay,Open,random,unknown,"Stephen Craig Paddock, opened fire from the 32...",59,...,585,1.0,64,NaN,NaN,Unclear,White,M,36.181271,-115.134132
4,5,San Francisco UPS shooting,"San Francisco, CA",2017-06-14,UPS facility,Close,coworkers,NaN,"Jimmy Lam, 38, fatally shot three coworkers an...",3,...,5,0.0,38,1.0,NaN,Yes,Asian,M,46.844325,-71.274327
5,6,Pennsylvania supermarket shooting,"Tunkhannock, PA",2017-06-07,Weis grocery,Close,coworkers,terrorism,"Randy Stair, a 24-year-old worker at Weis groc...",3,...,3,NaN,24,1.0,Weis grocery,Unclear,White,M,41.538516,-75.946844
6,7,Florida awning manufacturer shooting,"Orlando, Florida",2017-06-05,manufacturer Fiamma Inc.,Close,coworkers,unemployement,"John Robert Neumann, Jr., 45, a former employe...",5,...,5,NaN,45,1.0,manufacturer Fiamma Inc.,Unclear,NaN,M,28.542123,-81.379047
7,8,Rural Ohio nursing home shooting,"Kirkersville, Ohio",2017-05-12,a nursing home,Close,coworkers,NaN,"Thomas Hartless, 43, shot and killed a former ...",3,...,3,1.0,43,1.0,some nursing home,Yes,White,M,39.959508,-82.595718
8,9,Fresno downtown shooting,"Fresno, California",2017-04-18,a street in downtown,Open,random,racism,"Kori Ali Muhammad, 39, opened fire along a str...",3,...,3,NaN,39,NaN,NaN,Unclear,Black,M,36.729529,-119.708861
9,10,Fort Lauderdale airport shooting,"Fort Lauderdale, Florida",2017-01-06,baggage claim area of the airport,Close,random,terrorism,"Esteban Santiago, 26, flew from Alaska to Fort...",5,...,11,NaN,26,NaN,NaN,Yes,Latino,M,26.122308,-80.143379
10,11,Cascade Mall shooting,"Burlington, WA",2016-09-23,cosmetics section of a MacyÃ¢Â€Â™s department store,Close,women,terrorism,"Arcan Cetin, 20, killed a teen girl and three ...",5,...,5,NaN,20,NaN,NaN,Yes,NaN,M,40.807539,-91.112923
11,12,Baton Rouge police shooting,"Baton Rouge, LA",2016-07-17,NaN,Open,police,NaN,"Gavin Long, a former Marine who served in Iraq...",3,...,6,3.0,NaN,NaN,former Marine,Yes,Black,M,30.450746,-91.154551
12,13,Dallas police shooting,"Dallas, Texas",2016-07-07,at protest,Open,police,racism,"Micah Xavier Johnson, a 25-year-old Army veter...",5,...,16,5.0,25,NaN,Army veteran,Unclear,Black,M,32.776272,-96.796856
13,14,Orlando nightclub massacre,"Orlando, Florida",2016-06-12,at nightclub,Close,random,NaN,"Omar Mateen, 29, attacked the Pulse nighclub i...",49,...,102,0.0,29,NaN,NaN,Unclear,Other,M,28.542123,-81.379047
14,15,"Ferguson, MO Drive by","Ferguson, Missouri",2016-04-29,NaN,Open,random,NaN,A group of 15 to 20 people was gathered for a ...,0,...,4,0.0,0,NaN,NaN,Unknown,Unknown,Unknown,38.744217,-90.305391
15,16,"Forestville, Maryland Drive-by",NaN,2016-04-26,in street,Open,NaN,NaN,Shooter shot from his car at people standing o...,1,...,5,0.0,NaN,NaN,NaN,Unknown,Unknown,Unknown,38.845113,-76.874972
16,17,"Halifax County, VA",NaN,2016-04-24,crown,Open,random,NaN,Male shooter fired into crown when a deputy po...,0,...,6,0.0,NaN,NaN,NaN,Unknown,Black American or African American,Male,36.765971,-78.928344
17,18,Tire-Slashing revenge escalation,NaN,2016-04-21,block party,Open,random,frustration,Shooter was angry over fact that rival familie...,0,...,4,0.0,NaN,NaN,NaN,Unknown,Black American or African American,Male,39.290385,-76.612189
18,19,Chicago Rap video Shootout,NaN,2016-04-19,in a park,Open,random,NaN,Group of young men were in a park at 2 in the ...,1,...,5,0.0,NaN,NaN,NaN,Unknown,Unknown,Unknown,41.878114,-87.629798
19,20,Texas family murder-suicide,NaN,2016-04-19,Home,Close,Family,domestic dispute,Man killed his wife and two young children bef...,4,...,4,0.0,NaN,NaN,NaN,Unknown,White American or European American,Male,29.785785,-95.824396
20,21,Alabama highway random shooting,NaN,2016-04-19,along a highway,Open,random,NaN,Shooter fired from his car at two different lo...,1,...,4,0.0,NaN,NaN,NaN,Yes,White American or European American,Male,34.162040,-86.475543
21,22,Long Beach Street murder,NaN,2016-04-18,at street corner,Open,random,terrorism,Group of men were standing at a street corner ...,0,...,4,0.0,NaN,NaN,NaN,Unknown,Unknown,Unknown,33.770050,-118.193739
22,23,"Albuquerque, NM House party shooting",NaN,2016-04-09,at party,Close,uninvited guests,anger,A Man shot four uninvited party guests who wou...,0,...,4,0.0,NaN,NaN,NaN,Unknown,White American or European American,Male,35.085334,-106.605553
23,24,"Memphis, TN gas station shooting",NaN,2016-04-09,at gas station,Open,random,anger,Four people were shot below the waist at a gas...,0,...,4,0.0,NaN,NaN,NaN,Unknown,Unknown,Unknown,35.149534,-90.048980
24,25,Chicago Birthday Party Bus Shooting,NaN,2016-04-07,south shore,Open,birthday party bus,NaN,Birthday party bus was dropping off party goer...,0,...,5,0.0,NaN,NaN,NaN,Unknown,Unknown,Unknown,41.878114,-87.629798
25,26,"Albuquerque, NM Family restaurant shooting",NaN,2016-04-01,restaurant,Close,Family,NaN,The shooter killed two of his nephews at the r...,3,...,3,0.0,NaN,NaN,NaN,Unknown,Asian American,Male,35.085334,-106.605553
26,27,"Richmond, Virginia","Richmond, Virginia",2016-03-31,bus station,Open,Trooper,frustration,A man fatally shot a Virginia state trooper at...,2,...,3,0.0,NaN,NaN,NaN,Unknown,Black American or African American,Male,37.540725,-77.436048
27,28,"Louisburg, North Carolina","Louisburg, North Carolina",2016-03-26,NaN,NaN,NaN,terrorism,Three people were killed in a shooting at a ho...,3,...,3,NaN,NaN,NaN,NaN,Unknown,Black American or African American,Male,36.099039,-78.301106
28,29,"Lawrenceburg, Tennessee","Lawrenceburg, Tennessee",2016-03-25,in home,Close,Family,domestic dispute,The man was suspected of shooting his wife and...,2,...,3,0.0,NaN,NaN,NaN,Unknown,Unknown,Male,35.242302,-87.334739
29,30,"Greenhill, AL Family murder-suicide",NaN,2016-03-25,home in rural Alabama,Close,Family,domestic dispute,Husband murders his wife and injures his two s...,2,...,3,0.0,NaN,NaN,NaN,Yes,White American or European American,Male,34.759257,-86.602493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,294,Cleveland Elementary School,"Stockton, California",1989-01-17,Cleveland Elementary School,Close,Students+Teachers,terrorism,"On January 17, 1989, an unemployed 24-year-old...",6,...,35,0.0,24,0.0,NaN,Yes,White American or European American,Male,37.966318,-121.301877
294,295,New Orleans Downtown Post Office,"New Orleans, Louisiana",1988-12-14,main post office in downtown New Orleans,Close,NaN,NaN,"On December 14, 1988, a 39-year-old post offic...",0,...,4,0.0,39,1.0,Post Office,Unknown,Unknown,Male,30.068724,-89.931474
295,296,Oakland Elementary School,"Greenwood, South Carolina",1988-09-26,Oakland Elementary School,Close,Students+Teachers,psycho,"On September 26, 1988, an unemployed 19-year-o...",2,...,11,0.0,19,0.0,NaN,Yes,White American or European American,Male,34.192895,-82.153555
296,297,Comet Auto Parts and Montefiore School,"Chicago, Illinois",1988-09-22,NaN,Open+Close,random,terrorism,"On September 22, 1988, a 40-year-old Vietnam v...",5,...,6,1.0,40,NaN,NaN,No,Black American or African American,Male,41.839280,-87.688181
297,298,Hubbard Woods Elementary School,"Winnetka, Illinois",1988-05-20,Home+School,Close,Students,terrorism,"On May 20, 1988, a 30-year-old woman entered t...",2,...,8,0.0,30,NaN,NaN,Yes,White American or European American,Female,42.106488,-87.742111
298,299,Electromagnetic Systems Laboratory (ESL),"Sunnyvale, California",1988-02-16,ESL in Sunnyvale,Open+Close,Ex-Coworkers,revenge,"On February 16, 1988, a 39-year-old man arrive...",7,...,11,0.0,39,0.0,NaN,Yes,White American or European American,Male,37.383443,-122.025619
299,300,Pinellas Park High School,"Pinellas Park, Florida",1988-02-11,School,Close,NaN,frustration,"On February 11, 1988, two students age 15 and ...",1,...,3,0.0,"15,16",NaN,NaN,No,White American or European American,Male,27.848871,-82.710580
300,301,Palm Bay Shopping Centers,"Palm Bay, Florida",1987-04-23,NaN,Open,random,psycho,"On April 23, 1987, a 59-year-old retired libra...",6,...,20,0.0,59,NaN,NaN,Yes,White American or European American,Male,27.983890,-80.666627
301,302,Fergus County High School,"Lewistown, Montana",1986-12-04,Fergus County High School,Close,Teachers,failing exams,"On December 4, 1986, a 14-year-old student at ...",1,...,4,0.0,14,NaN,NaN,Yes,White American or European American,Male,47.037407,-109.484492
302,303,"Post office in Edmond, Oklahoma","Edmond, Oklahoma",1986-08-20,"Edmond, Oklahoma",Close,Coworkers,NaN,"On August 20, 1986, a 44-year-old postal worke...",15,...,20,0.0,44,1.0,Post Office,Yes,White American or European American,Male,35.668892,-97.414388
303,304,New York Technical College,"Brooklyn, New York",1986-08-12,New York Technical College in Brooklyn,Close,Teachers,revenge,"On August 12, 1986, a 29-year civil technology...",1,...,5,0.0,29,NaN,NaN,Yes,Black American or African American,Male,40.679276,-73.939513
304,305,Atlanta Post Office,"Atlanta, Georgia",1985-03-06,Atlanta Post Office,Close,Coworkers,anger,"On March 6, 1985, a 30-year-old employee at th...",2,...,3,0.0,30,1.0,Atlanta Post Office,Yes,Black American or African American,Male,33.762997,-84.423133
305,306,Goddard Junior High School,"Goddard, Kansas",1985-01-21,Goddard Junior High School,Close,Students+Teachers,NaN,"On January 21, 1985, a 14-year-old student ent...",1,...,4,0.0,14,NaN,NaN,Yes,White American or European American,Male,37.671294,-97.550705
306,307,McDonald's restaurant in San Ysidro,"San Ysidro, California",1984-07-18,McDonald's restaurant in San Ysidro,Close,random,psycho,"On July 18, 1984, a 41-year-old unemployed man...",22,...,40,0.0,41,0.0,NaN,Yes,White American or European American,Male,32.555556,-117.047656
307,308,Ianni's Club in Dallas,"Dallas, Texas",1984-06-29,lanni's dance club,Close,random,revenge,"On June 29, 1984, a 39-year-old man who was re...",6,...,7,0.0,39,NaN,NaN,Yes,White American or European American,Male,32.794806,-96.766311
308,309,49th Street Elementary School,"Los Angeles, California",1984-02-24,NaN,Open,Children,terrorism,"On February 24, a 28-year-old man began shooti...",3,...,14,0.0,28,NaN,NaN,Yes,Black American or African American,Male,34.176221,-118.539954
309,310,Johnston Post Office,"Johnston, South Carolina",1983-08-19,Johnston Post Office,Close,postmaster,anger,"On August 19, 1983, a 55-year-old former posta...",1,...,4,0.0,55,0.0,NaN,Yes,White American or European American,Male,33.832729,-81.805158
310,311,Wah Mee Club in Seattle,"Seattle, Washington",1983-02-18,Wah Mee Gambling Club,Close,random,terrorism,"On February 18, 1983, three man between the ag...",13,...,14,0.0,23,NaN,NaN,Unknown,Asian American,Male,47.621996,-122.323646
311,312,Welding shop in Miami,"Miami, Florida",1982-08-20,NaN,Close,welding shop employees,psycho,"On August 20, 1982, a 51-year-old teacher on p...",9,...,11,0.0,51,NaN,NaN,Yes,White American or European American,Male,25.796539,-80.208404
312,313,Valley High School,"Las Vegas, Nevada",1982-03-19,Valley High School,Close,Students+Teachers,NaN,"On March 19, 1982, a 17-year-old student walke...",1,...,3,0.0,17,NaN,NaN,Yes,White American or European American,Male,36.189319,-115.326487
313,314,University of South Carolina,"Columbia, South Carolina",1979-10-06,fraternity house party,Close,Students,NaN,"On October 6, 1979, a 19-year-old student at U...",2,...,7,0.0,19,NaN,NaN,Unknown,Black American or African American,Male,34.050988,-80.820775
314,315,Grover Cleveland Elementary School,"San Diego, California",1979-01-29,NaN,Open,Children,terrorism,"On January 29, 1979, a 16-year-old opened fire...",2,...,11,0.0,16,NaN,NaN,Yes,White American or European American,Female,32.863573,-117.128163
315,316,Cal State Fullerton,"Fullerton, California",1976-07-12,California State University,Close,random,terrorism,"On July 12, 1976, a 37-year-old custodian at C...",7,...,9,0.0,37,1.0,California State University,Yes,White American or European American,Male,33.884042,-117.927850
316,317,Los Angeles Computer Learning Center,"Los Angeles, California",1976-02-19,Los Angeles Computer School,Close,Students,anger,"On February 19, 1976, a 18-year-old student at...",1,...,8,0.0,18,NaN,NaN,Unknown,White American or European American,Male,34.176221,-118.539954
317,318,Olean High School,"Olean, New York",1974-12-30,NaN,Open+Close,random,terrorism,"On December 30, 1974, a 17-year-old honor stud...",3,...,10,0.0,17,NaN,NaN,No,White American or European American,Male,42.081854,-78.432139
318,319,Clara Barton Elementary School,"Chicago, Illinois",1974-01-17,Clara Barton Elementary School,Close,Teachers,anger,"On January 17, 1974, a 14-year-old student ent...",1,...,4,0.0,14,NaN,NaN,Yes,Unknown,Male,41.839280,-87.688181
319,320,New Orleans Police Shootings,"New Orleans, Louisiana",1972-12-31,NaN,NaN,random,psycho,"On New Year's Eve in 1972, a 23-year-old ex-Na...",10,...,22,4.0,23,NaN,NaN,Yes,Black American or African American,Male,30.068724,-89.931474
320,321,St. Aloysius Church,"Spokane, Washington",1971-11-11,Church,Close,random,terrorism,"On November 11, 1971, a former MIT student ent...",2,...,5,0.0,NaN,NaN,NaN,Yes,White American or European American,Male,47.673674,-117.415984
321,322,Rose-Mar College of Beauty,"Mesa, Arizona",1966-11-12,Rose-Mar College of Beauty,Close,random,terrorism,"On November 12, 1966, an 18-year-old high scho...",5,...,6,0.0,18,NaN,NaN,Yes,White American or European American,Male,33.422687,-111.816320
322,323,University of Texas at Austin,"Austin, Texas",1966-08-01,University of Texas,Close,random,terrorism,"On August 1, 1966, a 25-year-old engineering s...",17,...,48,0.0,25,NaN,NaN,Yes,White American or European American,Male,30.198887,-97.844159

In [48]:
df.to_csv('massshootings_2.csv')